# Generated by Django 5.1.1 on 2025-01-23 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_artist',
        ),
    ]
