# Generated by Django 5.1.1 on 2025-01-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_song_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
