name: Django CI Workflow

on:
  push:
    branches:
      - main  # Run on push to the main branch
  pull_request:
    branches:
      - main  # Run on PRs to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Set the operating system to Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the code from the repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Set the Python version for your Django project

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install project dependencies

    - name: Set up PostgreSQL (if using PostgreSQL)
      uses: docker://postgres:12  # Use Docker to set up a PostgreSQL service
      env:
        POSTGRES_DB: test_db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres

    - name: Run database migrations
      run: |
        python manage.py migrate  # Apply migrations

    - name: Run tests
      run: |
        python manage.py test  # Run the Django test suite

    - name: Collect static files
      run: |
        python manage.py collectstatic --noinput  # Collect static files for deployment
